// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"

	"github.com/rs/zerolog/log"
)

func NewCharacterWeaponTable() *CharacterWeaponTable {
	return &CharacterWeaponTable{records: make(map[string]*CharacterWeaponRecord,1994)}
}

type CharacterWeaponTable struct {
	records map[string]*CharacterWeaponRecord
}

type CharacterWeaponRecord struct {
	Index string

	ItemName string

	WeaponType string

	Stand string

	Walk string

	SwingAttack string

	SwingFinalAttack string

	StabAttack string

	StabFinalAttack string

	ShootAttack string

	ShootFinalAttack string

	desc string
}

func (t *CharacterWeaponTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &CharacterWeaponRecord{}
		rec.Index = record[0]
		rec.ItemName = record[1]
		rec.WeaponType = record[2]
		rec.Stand = record[3]
		rec.Walk = record[4]
		rec.SwingAttack = record[5]
		rec.SwingFinalAttack = record[6]
		rec.StabAttack = record[7]
		rec.StabFinalAttack = record[8]
		rec.ShootAttack = record[9]
		rec.ShootFinalAttack = record[10]
		rec.desc = record[11]
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *CharacterWeaponTable) Get (key string) (CharacterWeaponRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return CharacterWeaponRecord{}, false
	}
	return *rec, true
}

func (t *CharacterWeaponTable) GetAll() []CharacterWeaponRecord {
	all := make([]CharacterWeaponRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
