// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewClickerMonsterTable() *ClickerMonsterTable {
	return &ClickerMonsterTable{records: make(map[string]*ClickerMonsterRecord,4)}
}

type ClickerMonsterTable struct {
	records map[string]*ClickerMonsterRecord
}

type ClickerMonsterRecord struct {
	Index string

	Prob float64

	ItemIndex int64

	ItemCount int64

	Hp int64

	ModelID string
}

func (t *ClickerMonsterTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &ClickerMonsterRecord{}
		rec.Index = record[0]
		{
			floatVal, err := strconv.ParseFloat(record[1], 64)
			if err != nil {
				return err
			}
			rec.Prob = floatVal
		}
		{
			intVal, err := strconv.ParseInt(record[2], 10, 64)
			if err != nil {
				return err
			}
			rec.ItemIndex = intVal
		}
		{
			intVal, err := strconv.ParseInt(record[3], 10, 64)
			if err != nil {
				return err
			}
			rec.ItemCount = intVal
		}
		{
			intVal, err := strconv.ParseInt(record[4], 10, 64)
			if err != nil {
				return err
			}
			rec.Hp = intVal
		}
		rec.ModelID = record[5]
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *ClickerMonsterTable) Get (key string) (ClickerMonsterRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return ClickerMonsterRecord{}, false
	}
	return *rec, true
}

func (t *ClickerMonsterTable) GetAll() []ClickerMonsterRecord {
	all := make([]ClickerMonsterRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
