// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewCreateCharacter1HWeaponTable() *CreateCharacter1HWeaponTable {
	return &CreateCharacter1HWeaponTable{records: make(map[string]*CreateCharacter1HWeaponRecord,31)}
}

type CreateCharacter1HWeaponTable struct {
	records map[string]*CreateCharacter1HWeaponRecord
}

type CreateCharacter1HWeaponRecord struct {
	Index string

	Name string

	MaleProb float64

	FemaleProb float64
}

func (t *CreateCharacter1HWeaponTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &CreateCharacter1HWeaponRecord{}
		rec.Index = record[0]
		rec.Name = record[1]
		{
			floatVal, err := strconv.ParseFloat(record[2], 64)
			if err != nil {
				return err
			}
			rec.MaleProb = floatVal
		}
		{
			floatVal, err := strconv.ParseFloat(record[3], 64)
			if err != nil {
				return err
			}
			rec.FemaleProb = floatVal
		}
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *CreateCharacter1HWeaponTable) Get (key string) (CreateCharacter1HWeaponRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return CreateCharacter1HWeaponRecord{}, false
	}
	return *rec, true
}

func (t *CreateCharacter1HWeaponTable) GetAll() []CreateCharacter1HWeaponRecord {
	all := make([]CreateCharacter1HWeaponRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
