// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewCreateCharacterTable() *CreateCharacterTable {
	return &CreateCharacterTable{records: make(map[string]*CreateCharacterRecord, 17)}
}

type CreateCharacterTable struct {
	records map[string]*CreateCharacterRecord
}

type CreateCharacterRecord struct {
	Category string

	HoldingProb float64
}

func (t *CreateCharacterTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &CreateCharacterRecord{}
		rec.Category = record[0]
		{
			floatVal, err := strconv.ParseFloat(record[1], 64)
			if err != nil {
				return err
			}
			rec.HoldingProb = floatVal
		}
		_, ok := t.records[rec.Category]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Category)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Category] = rec
	}
	return nil
}

func (t *CreateCharacterTable) Get(key string) (CreateCharacterRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return CreateCharacterRecord{}, false
	}
	return *rec, true
}

func (t *CreateCharacterTable) GetAll() []CreateCharacterRecord {
	all := make([]CreateCharacterRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
