// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewCreateCharacterSkinTable() *CreateCharacterSkinTable {
	return &CreateCharacterSkinTable{records: make(map[string]*CreateCharacterSkinRecord,18)}
}

type CreateCharacterSkinTable struct {
	records map[string]*CreateCharacterSkinRecord
}

type CreateCharacterSkinRecord struct {
	Index string

	Name string

	MaleProb float64

	FemaleProb float64
}

func (t *CreateCharacterSkinTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &CreateCharacterSkinRecord{}
		rec.Index = record[0]
		rec.Name = record[1]
		{
			floatVal, err := strconv.ParseFloat(record[2], 64)
			if err != nil {
				return err
			}
			rec.MaleProb = floatVal
		}
		{
			floatVal, err := strconv.ParseFloat(record[3], 64)
			if err != nil {
				return err
			}
			rec.FemaleProb = floatVal
		}
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *CreateCharacterSkinTable) Get (key string) (CreateCharacterSkinRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return CreateCharacterSkinRecord{}, false
	}
	return *rec, true
}

func (t *CreateCharacterSkinTable) GetAll() []CreateCharacterSkinRecord {
	all := make([]CreateCharacterSkinRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
