// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewCreateCharacterShoesTable() *CreateCharacterShoesTable {
	return &CreateCharacterShoesTable{records: make(map[string]*CreateCharacterShoesRecord,50)}
}

type CreateCharacterShoesTable struct {
	records map[string]*CreateCharacterShoesRecord
}

type CreateCharacterShoesRecord struct {
	Index string

	Name string

	MaleProb float64

	FemaleProb float64
}

func (t *CreateCharacterShoesTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &CreateCharacterShoesRecord{}
		rec.Index = record[0]
		rec.Name = record[1]
		{
			floatVal, err := strconv.ParseFloat(record[2], 64)
			if err != nil {
				return err
			}
			rec.MaleProb = floatVal
		}
		{
			floatVal, err := strconv.ParseFloat(record[3], 64)
			if err != nil {
				return err
			}
			rec.FemaleProb = floatVal
		}
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *CreateCharacterShoesTable) Get (key string) (*CreateCharacterShoesRecord, bool) {
	rec, ok := t.records[key]
	return rec, ok
}

