// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"

	"github.com/rs/zerolog/log"
)

func NewItemTable() *ItemTable {
	return &ItemTable{records: make(map[string]*ItemRecord,616)}
}

type ItemTable struct {
	records map[string]*ItemRecord
}

type ItemRecord struct {
	Index string

	Category string

	ItemName string

	RUID string
}

func (t *ItemTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &ItemRecord{}
		rec.Index = record[0]
		rec.Category = record[1]
		rec.ItemName = record[2]
		rec.RUID = record[3]
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *ItemTable) Get (key string) (*ItemRecord, bool) {
	rec, ok := t.records[key]
	return rec, ok
}

