// Code generated by ANY_NAME. DO NOT EDIT.
package table

import (
	"encoding/csv"
	"errors"
	"os"
	"strconv"

	"github.com/rs/zerolog/log"
)

func NewItemOptionTable() *ItemOptionTable {
	return &ItemOptionTable{records: make(map[string]*ItemOptionRecord,616)}
}

type ItemOptionTable struct {
	records map[string]*ItemOptionRecord
}

type ItemOptionRecord struct {
	Index string

	ItemName string

	Bound bool

	Male bool

	Female bool
}

func (t *ItemOptionTable) Load(csvPath string) error {
	var err error
	file, err := os.Open(csvPath)
	if err != nil {
		return err
	}
	defer file.Close()

	r := csv.NewReader(file)
	records, err := r.ReadAll()
	if err != nil {
		return err
	}

	for _, record := range records[1:] {
		rec := &ItemOptionRecord{}
		rec.Index = record[0]
		rec.ItemName = record[1]
		{
			boolVal, err := strconv.ParseBool(record[2])
			if err != nil {
				return err
			}
			rec.Bound = boolVal
		}
		{
			boolVal, err := strconv.ParseBool(record[3])
			if err != nil {
				return err
			}
			rec.Male = boolVal
		}
		{
			boolVal, err := strconv.ParseBool(record[4])
			if err != nil {
				return err
			}
			rec.Female = boolVal
		}
		_, ok := t.records[rec.Index]
		if ok {
			log.Printf("Duplicate key '%v' found in CSV, skipping record.\n", rec.Index)
			err = errors.New("duplicate key")
			continue
		}
		t.records[rec.Index] = rec
	}
	return nil
}

func (t *ItemOptionTable) Get (key string) (ItemOptionRecord, bool) {
	rec, ok := t.records[key]
	if !ok {
		return ItemOptionRecord{}, false
	}
	return *rec, true
}

func (t *ItemOptionTable) GetAll() []ItemOptionRecord {
	all := make([]ItemOptionRecord, 0, len(t.records))
	for _, rec := range t.records {
		all = append(all, *rec)
	}
	return all
}
