package user

import "MScannot206/shared"

const USER_CHECK_CHARACTER_NAME_UNKNOWN_ERROR = "USER_CHECK_CHARACTER_NAME_UNKNOWN_ERROR"
const USER_CHARACTER_NAME_ALREADY_EXISTS_ERROR = "USER_CHARACTER_NAME_ALREADY_EXISTS_ERROR"

const USER_CREATE_CHARACTER_UNKNOWN_ERROR = "USER_CREATE_CHARACTER_UNKNOWN_ERROR"
const USER_CHARACTER_SLOT_INVALID_ERROR = "USER_CHARACTER_SLOT_INVALID_ERROR"
const USER_CHARACTER_SLOT_ALREADY_EXISTS_ERROR = "USER_CHARACTER_SLOT_ALREADY_EXISTS_ERROR"

func init() {
	shared.RegisterError(USER_CHECK_CHARACTER_NAME_UNKNOWN_ERROR, "캐릭터 이름 확인 중 알 수 없는 오류")
	shared.RegisterError(USER_CHARACTER_NAME_ALREADY_EXISTS_ERROR, "이미 존재하는 캐릭터 이름입니다.")

	shared.RegisterError(USER_CREATE_CHARACTER_UNKNOWN_ERROR, "캐릭터 생성 중 알 수 없는 오류")
	shared.RegisterError(USER_CHARACTER_SLOT_INVALID_ERROR, "잘못된 캐릭터 슬롯입니다.")
	shared.RegisterError(USER_CHARACTER_SLOT_ALREADY_EXISTS_ERROR, "이미 해당 슬롯에 캐릭터가 존재합니다.")
}
